### ISSUE TITLE
Refreshing the page causes me to lose my pokemon

### ISSUE THREAD

**Issue by ChristienGuy** [d-elv/pokeApi#1]
Also I can't share it with a friend. 

Is there some way to update the URL when you search for a pokemon so that we can share the URL and it'll load the right details?

**Comment by d-elv** [comment]
Ah yes, I reckon I can do a bit of research and fix the refresh part. I've not really done any URL updating yet so that would also be a neat thing to look into! Certainly I've never interfaced with hosting or sharing links, Jack mentioned using Netlify as a hosting platform?

That's also given me an idea for adding a dropdown or similar sort of list that a user can sift through to pick out a pokemon, as opposed to having to know the name and type it in perfectly.

**Comment by ChristienGuy** [comment]
I wouldn't worry about hosting right now that's kinda separate. 

Just being able to go to like localhost:3000/pikachu or localhost:3000/pokemon/12 or something and have it load the right data would be enough! 

The logic that'd make that work is the same logic that would work when it's hosted somewhere. That would also solve the refresh part cause then when you refresh it just reloads the same url that loads that specific pokemon data.

As always, happy to hop on a call and talk through the concepts in more detail.

**Comment by d-elv** [comment]
Solved in latest branch merge.
